# Generated by Django 3.1.4 on 2020-12-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('e_mail', models.EmailField(default=None, max_length=254)),
                ('name', models.CharField(default=None, max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('company_name', models.CharField(default=None, max_length=100, null=True)),
                ('sector', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=13, null=True)),
                ('website', models.CharField(default='', max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default=None, max_length=100)),
                ('job_description', models.CharField(default=None, max_length=100)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(default=None, null=True)),
                ('req_departments', models.CharField(default=None, max_length=100, null=True)),
                ('employer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_news', models.BooleanField(default=False)),
                ('not_messages', models.BooleanField(default=False)),
                ('not_matches', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('school_name', models.CharField(default=None, max_length=100, null=True)),
                ('department', models.CharField(default=None, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('cgpa', models.FloatField(default=0.0, null=True)),
                ('e_mail', models.EmailField(default=None, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.skill')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.job')),
                ('skill', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.job')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
