# Generated by Django 3.1.1 on 2020-12-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_news', models.BooleanField(default=False)),
                ('not_messages', models.BooleanField(default=False)),
                ('not_matches', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='username',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='job',
            name='condition_1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='condition_2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='condition_3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='condition_4',
        ),
        migrations.RemoveField(
            model_name='job',
            name='condition_5',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='condition_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='condition_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='condition_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='condition_4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='condition_5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student'),
        ),
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='e_mail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='employer',
            name='phone',
            field=models.CharField(default=None, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='sector',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='due_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='req_departments',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='e_mail',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.job'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='surname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.skill')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.job')),
                ('skill', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.skill')),
            ],
        ),
    ]
