# Generated by Django 3.1.4 on 2020-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='e_mail',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
