# Generated by Django 3.1.1 on 2020-12-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201223_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='sector',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
