# Generated by Django 3.1.1 on 2021-01-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201227_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
