# Generated by Django 3.1.4 on 2021-01-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210106_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskill',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
