# Generated by Django 3.1.4 on 2021-01-12 09:42

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_jobskill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='profile_img',
            field=models.ImageField(default='comp-logo.jpg', upload_to=mainapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(default='student-pp.png', upload_to=mainapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='type',
            field=models.IntegerField(default=5),
        ),
    ]
