# Generated by Django 3.1.1 on 2021-01-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210112_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
