# Generated by Django 3.1.4 on 2021-01-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210118_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=250)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
